CREATE OR REPLACE VIEW CICD_DEMO_DB.TESTSCHEMA2.V_TESTVIEW AS
SELECT
    COL1,
    COL2
FROM
TESTSCHEMA2.TESTTABLE; 

CREATE OR REPLACE VIEW TESTSCHEMA2.V_TESTVIEW14 AS
SELECT
    COL1,
    COL2
FROM
TESTSCHEMA2.TESTTABLE; 



CREATE OR REPLACE VIEW TESTSCHEMA2.V_TESTVIEW12 AS
SELECT
    COL1,
    COL2
FROM
TESTSCHEMA2.TESTTABLE; 