CREATE OR REPLACE VIEW TESTSCHEMA.V_TESTVIEW AS
SELECT
    COL1,
    COL2
FROM
TESTSCHEMA.TESTTABLE; 

CREATE OR REPLACE VIEW TESTSCHEMA.V_TESTVIEW13 AS
SELECT
    COL1,
    COL2
FROM
TESTSCHEMA.TESTTABLE; 

CREATE OR REPLACE VIEW TESTSCHEMA.V_TESTVIEW11 AS
SELECT
    COL1,
    COL2
FROM
TESTSCHEMA.TESTTABLE; 

CREATE OR REPLACE VIEW TESTSCHEMA.V_TESTVIEW12 AS
SELECT
    COL1,
    COL2
FROM
TESTSCHEMA.TESTTABLE; 