CREATE OR REPLACE VIEWd TESTSCHEMA.V_TESTVIEW AS
SELECT
    COL1,
    COL2
FROM
TESTSCHEMA.TESTTABLE; 

CREATE OR REPLACE VIEW TESTSCHEMA.V_TESTVIEW14 AS
SELECT
    COL1,
    COL2
FROM
TESTSCHEMA.TESTTABLE; 

CREATE OR REPLACE VIEW TESTSCHEMA.V_TESTVIEW114 AS
SELECT
    COL1,
    COL2
FROM
TESTSCHEMA.TESTTABLE; 

CREATE OR REPLACE VIEW TESTSCHEMA.V_TESTVIEW12 AS
SELECT
    COL1,
    COL2
FROM
TESTSCHEMA.TESTTABLE; 