use  CICD_DEMO_DB;

CREATE TABLE IF NOT EXISTS CICD_DEMO_DB.TESTSCHEMA2.TESTTABLE (
    COL1 VARCHAR,
    COL2 NUMBER,
    COL3 VARCHAR(255)
);
CREATE TABLE IF NOT EXISTS CICD_DEMO_DB.TESTSCHEMA2.TESTTABLE48 (
    COL1 VARCHAR,
    COL2 NUMBER,
    COL3 VARCHAR(255)
);