CREATE TABLE IF NOT EXISTS TESTSCHEMA.TESTTABLE67 (
    COL1 VARCHAR,
    COL2 NUMBER,
    COL3 VARCHAR(255)
);
CREATE TABLE IF NOT EXISTS TESTSCHEMA.TESTTABLE48 (
    COL1 VARCHAR,
    COL2 NUMBER,
    COL3 VARCHAR(255)
);