CREATE TABLE IF NOT EXISTS TESTSCHEMA.TESTTABLE (
    COL1 VARCHAR,
    COL2 NUMBER,
    COL3 VARCHAR(255)
);
CREATE TABLE IF NOT EXISTS TESTSCHEMA.TESTTABLE22 (
    COL1 VARCHAR,
    COL2 NUMBER,
    COL3 VARCHAR(255)
);